In [1]:
# numpy 불러오기 
import numpy as np

In [3]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [5]:
# numpy를 이용하여 1차원 배열로 변형하기 

arr1 = np.array(data1)  # 숫자 타입을 통일시킴
# 문자와 숫자를 같이 못씀. 같은 type만 가능 
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
# 배열의 크기 확인
arr1.shape 
# 5개의 가로의 데이터가 있다 

(5,)

In [7]:
# 2차원 List
data2 = [
        [1,2,3,4],
        [5,6,7,8],
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
# numpy로 2차원 배열로 변형
arr2 = np.array(data2)
arr2
# 2행 4열 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.shape

(2, 4)

In [12]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.zeros([3,5,2])
# 2차원의 [5,2]를 3이라는 높이만큼 쌓음
# 즉, 3page

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
# 1로만 구성된 배열생성 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.full(5,10)
# 10을 5개 만듦

array([10, 10, 10, 10, 10])

In [18]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# 숫자 8로 구성된 3행 5열의 배열 구성 
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [27]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr3 = np.array([1,2,3,4,5],dtype =np.int64)
arr3.dtype
arr3

array([1, 2, 3, 4, 5])

In [39]:
# data type 변경 
# 소수형으로 
float_arr3 = arr3.astype(np.float64)
float_arr3.dtype

dtype('float64')

In [40]:
float_arr3

array([1., 2., 3., 4., 5.])

In [37]:
# 연산 
arr1 = np.array([
    [1,2,3],
    [4,5,6]
                ],dtype=np.float64)
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
# 연산 
arr2 = np.array([
            [7,8,9],
            [10,11,12],
                ],dtype=np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [41]:
arr1 + arr2
# 같은 위치끼리 더하기 

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [42]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [43]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [44]:
#나눗셈
arr1 /arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [45]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [46]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [47]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5]

5

In [52]:
arr[5:9] 

array([5, 6, 7, 8])

In [53]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [54]:
arr[8:]  # 8~9 끝까지 

array([12,  9])

# 2차원 배열

In [55]:
arr2d = np.array([
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
        ]
)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
arr2d.dtype
# numpy에서만 dtype

dtype('int64')

In [61]:
# 2번 행의 자료 출력 
arr2d[2]

array([ 9, 10, 11, 12])

In [62]:
# 2
arr2d[2,]

array([ 9, 10, 11, 12])

In [64]:
# 3 
arr2d[2,:]

array([ 9, 10, 11, 12])

In [66]:
arr2d[:,1]   # 1번째 칼럼의 모든 행 데이터 

array([ 2,  6, 10, 14])

In [67]:
arr2d[:,1:3]   # 1~2번째 칼럼의 모든 행 데이터 

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [70]:
# 1 ~ 2번행의 자료 출력 
arr2d[1:3,]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
# 3번열의 자료 출력 
arr2d[:,3]

array([ 4,  8, 12, 16])

In [73]:
# 0,1 열의 자료 출력 
arr2d[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [74]:
# 1행 2열의 자료 출력 
arr2d[1,2]

7

In [75]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [79]:
arr2d[0:2,1:3] = 0

In [80]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수발생
- rand : 0 ~ 1사이의 균일 분포 
- randn: 가우시안 표준 정규 분표 
- ranint : 균일 분표의 정수 난수 

### Boolean Indexing


In [111]:
names = np.array(["Charles","Kenny","Hayoung","Charles","Hayoung","Kenny","Kenny"])
data = np.random.randn(7,4)

In [90]:
names
# u7 = 아스키코드는 7비트 필요 

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [91]:
# 크기
names.shape
# 7행 

(7,)

In [108]:
data

array([[ 1.10327257, -0.26079854,  1.36419803, -1.23117372],
       [-0.24241602,  1.46417435, -0.90194235,  1.21615418],
       [-2.08107472, -0.2134623 , -0.65996822, -1.41967961],
       [ 1.03095688,  0.93429522, -1.31958724,  0.53695172],
       [ 1.95500065,  1.21764252, -0.10727288, -0.63436021],
       [-0.26275897, -0.12890105,  0.41965183,  0.12001467],
       [ 0.44627643,  0.38736721, -1.22318985,  0.93057311]])

In [93]:
# 7행 4열
data.shape

(7, 4)

In [94]:
# Mask를 이용한 추출 
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [95]:
data[names == "Charles",:]
# true인 행 

array([[-0.72910612, -0.28462325,  0.19445559, -0.70146558],
       [ 1.661863  , -0.45737715,  0.59898873, -1.07636757]])

In [96]:
# 둘 중 하나라도 true 인 것 출력 
data[(names == "Charles")| (names == "Kenny"),:]

array([[-0.72910612, -0.28462325,  0.19445559, -0.70146558],
       [-1.64339433,  0.12664802, -0.96595672, -0.43510963],
       [ 1.661863  , -0.45737715,  0.59898873, -1.07636757],
       [ 1.23144217,  2.25332193,  1.522213  , -1.1723123 ],
       [-3.20154025, -0.1190398 ,  0.42222232,  0.17653361]])

In [97]:
data[:]

array([[-0.72910612, -0.28462325,  0.19445559, -0.70146558],
       [-1.64339433,  0.12664802, -0.96595672, -0.43510963],
       [ 0.06267885,  0.12958254,  0.56307838, -0.37082822],
       [ 1.661863  , -0.45737715,  0.59898873, -1.07636757],
       [-0.41661879, -0.36459971,  0.08100078, -1.25401282],
       [ 1.23144217,  2.25332193,  1.522213  , -1.1723123 ],
       [-3.20154025, -0.1190398 ,  0.42222232,  0.17653361]])

In [99]:
# 4번째 
data[:,3]

array([-0.70146558, -0.43510963, -0.37082822, -1.07636757, -1.25401282,
       -1.1723123 ,  0.17653361])

In [112]:
# data의 4번째 열 값중 0보다 작은 것의 mask 만들기
# 만든 후 데이터에 넣어 행에 넣기 
data[data[:, 3] < 0, :]

array([[ 1.40062356, -0.59379801,  0.8197324 , -0.52344365],
       [ 0.42323634, -1.15919496, -0.94453232, -1.71544344],
       [-1.15029125, -0.31209403,  2.57984098, -1.69044994]])

In [113]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기 
data[data[:,3] < 0,:] = 0

In [114]:
data

array([[ 0.38840376, -0.51074291, -1.21060112,  0.41957722],
       [ 0.14038681,  0.27410333, -0.27162671,  1.2757358 ],
       [ 1.59471271, -0.5296734 , -1.28887955,  0.02799604],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.26408186, -1.96331473,  1.36936263,  0.7236626 ]])

In [115]:
# 정렬 
arr = np.random.rand(8)
arr

array([0.39476714, 0.09383371, 0.20565978, 0.6934879 , 0.5546735 ,
       0.05455653, 0.17208914, 0.20015183])

In [116]:
# 오름차순 정렬
np.sort(arr)

array([0.05455653, 0.09383371, 0.17208914, 0.20015183, 0.20565978,
       0.39476714, 0.5546735 , 0.6934879 ])

In [117]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.6934879 , 0.5546735 , 0.39476714, 0.20565978, 0.20015183,
       0.17208914, 0.09383371, 0.05455653])

In [118]:
arr = np.random.rand(5,3)
arr

array([[0.81299194, 0.98378934, 0.75815951],
       [0.04377867, 0.04880121, 0.887753  ],
       [0.42301969, 0.61032355, 0.4403465 ],
       [0.1911767 , 0.44874647, 0.07144821],
       [0.01791425, 0.36093556, 0.72018292]])

In [120]:
np.sort(arr, axis=0) # 열방향 

array([[0.01791425, 0.04880121, 0.07144821],
       [0.04377867, 0.36093556, 0.4403465 ],
       [0.1911767 , 0.44874647, 0.72018292],
       [0.42301969, 0.61032355, 0.75815951],
       [0.81299194, 0.98378934, 0.887753  ]])

In [121]:
np.sort(arr, axis=1) # 행방향 

array([[0.75815951, 0.81299194, 0.98378934],
       [0.04377867, 0.04880121, 0.887753  ],
       [0.42301969, 0.4403465 , 0.61032355],
       [0.07144821, 0.1911767 , 0.44874647],
       [0.01791425, 0.36093556, 0.72018292]])

In [124]:
np.sort(arr, axis=0)[::-1] # 열방향 , 내림차순

array([[0.81299194, 0.98378934, 0.887753  ],
       [0.42301969, 0.61032355, 0.75815951],
       [0.1911767 , 0.44874647, 0.72018292],
       [0.04377867, 0.36093556, 0.4403465 ],
       [0.01791425, 0.04880121, 0.07144821]])

In [125]:
np.sort(arr, axis=1)[:,::-1] # 행방향 , 내림차순

array([[0.98378934, 0.81299194, 0.75815951],
       [0.887753  , 0.04880121, 0.04377867],
       [0.61032355, 0.4403465 , 0.42301969],
       [0.44874647, 0.1911767 , 0.07144821],
       [0.72018292, 0.36093556, 0.01791425]])

In [126]:
# 중복제거 
np.unique(names)


array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape

In [128]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [129]:
arr.shape

(8,)

In [130]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
# 3차원 배열로 변경 
arr2 = np.reshape(arr, (2,2,2)) # page,row,column
arr2


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [132]:
# 2차원 배열을 1차원으로 변경 
arr3 = arr1.reshape(-1,1)
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [139]:
arr4 = arr2.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
# 3차원을 1차원으로 표시 
arr4 = arr2.reshape(-1,1)
arr4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [141]:
# 3차원을 1차원으로 표시  # 딥러닝
arr4 = arr2.reshape(-1,1,1)
arr4

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]]])

In [140]:
arr3 == arr4
# 단위행렬 

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])