# 서울시 CCTV 현황 분석 및 인구 현황 분석

### CCTV 설치현황

In [1]:
import pandas as pd

In [3]:
CCTV_seoul = pd.read_excel("../Data/CCTV_in_Seoul_2018.xlsx")
CCTV_seoul.head()

기관명    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강남구  5221    1944.0  195.0  316.0    430    546    765    577    448
1  강동구  1879     303.0  387.0  134.0     59    144    194    273    385
2  강북구  1265     243.0   88.0  141.0     74    145    254      1    319
3  강서구  1617     219.0  155.0  118.0    230    187    190    264    254
4  관악구  3985     430.0   56.0  419.0    487    609    619    694    671

In [4]:
# 컬럼 확인 
CCTV_seoul.columns

Index(['기관명', '소계', '2011년 이전', '2012년', '2013년', '2014년', '2015년', '2016년',
       '2017년', '2018년'],
      dtype='object')

In [5]:
CCTV_seoul.columns[0]

'기관명'

In [6]:
# 기관명 -> 구별로 변경 
CCTV_seoul.rename(columns={"기관명":"구별"},inplace=True)

In [7]:
CCTV_seoul.head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강남구  5221    1944.0  195.0  316.0    430    546    765    577    448
1  강동구  1879     303.0  387.0  134.0     59    144    194    273    385
2  강북구  1265     243.0   88.0  141.0     74    145    254      1    319
3  강서구  1617     219.0  155.0  118.0    230    187    190    264    254
4  관악구  3985     430.0   56.0  419.0    487    609    619    694    671

In [8]:
# NaN을 확인하고 NaN을 0으로 대체 
CCTV_seoul.isnull().sum()

구별          0
소계          0
2011년 이전    2
2012년       2
2013년       2
2014년       0
2015년       0
2016년       0
2017년       0
2018년       0
dtype: int64

In [15]:
CCTV_seoul=CCTV_seoul.fillna(0)

In [16]:
CCTV_seoul.isnull().sum()

구별          0
소계          0
2011년 이전    0
2012년       0
2013년       0
2014년       0
2015년       0
2016년       0
2017년       0
2018년       0
dtype: int64

---
### 서울 인구 데이터프레임

In [18]:
seoul_pop = pd.read_excel("../Data/population_in_Seoul_2020.xlsx")
seoul_pop.head()
# 1,3,6,9,13

report Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0        기간        자치구         세대         인구         인구         인구         인구   
1        기간        자치구         세대         합계         합계         합계        한국인   
2        기간        자치구         세대          계         남자         여자          계   
3  2020.1/4         합계    4354006   10013781    4874995    5138786    9733655   
4  2020.1/4        종로구      74151     161984      78271      83713     151217   

  Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  \
0         인구         인구         인구          인구          인구       세대당인구   
1        한국인        한국인      등록외국인       등록외국인       등록외국인       세대당인구   
2         남자         여자          계          남자          여자       세대당인구   
3    4742217    4991438     280126      132778      147348        2.24   
4      73704      77513      10767        4567        6200        2.04   

  Unnamed: 13  
0    65세이상고령자  
1    65세이상고령자  
2    65세이상고령자  
3     1518239  
4       28073

In [21]:
seoul_pop2 =seoul_pop.iloc[:,[1,3,6,9,13]]
seoul_pop2.head()

Unnamed: 1 Unnamed: 3 Unnamed: 6 Unnamed: 9 Unnamed: 13
0        자치구         인구         인구         인구    65세이상고령자
1        자치구         합계        한국인      등록외국인    65세이상고령자
2        자치구          계          계          계    65세이상고령자
3         합계   10013781    9733655     280126     1518239
4        종로구     161984     151217      10767       28073

In [22]:
seoul_pop2.columns =['자치구','계','계.1','계2','65세이상고령자']

In [23]:
seoul_pop2.head()

자치구         계      계.1      계2  65세이상고령자
0  자치구        인구       인구      인구  65세이상고령자
1  자치구        합계      한국인   등록외국인  65세이상고령자
2  자치구         계        계       계  65세이상고령자
3   합계  10013781  9733655  280126   1518239
4  종로구    161984   151217   10767     28073

In [31]:
# 불러올 때 부분만 가져오기 
pop_seoul = pd.read_excel("../Data/population_in_Seoul_2020.xlsx",
                        header=3,      # 헤더를 쓸 행의 번호  
                        usecols="B,D,G,J,N"         # 엑셀에서만 가능함 
)
pop_seoul.head()

자치구         계      계.1     계.2  65세이상고령자
0   합계  10013781  9733655  280126   1518239
1  종로구    161984   151217   10767     28073
2   중구    136469   126175   10294     23794
3  용산구    246165   229579   16586     39439
4  성동구    307193   299042    8151     44728

In [32]:
# 이름변경 
pop_seoul.columns =['구별','인구수','한국인','외국인','고령자']

In [33]:
pop_seoul.head()

구별       인구수      한국인     외국인      고령자
0   합계  10013781  9733655  280126  1518239
1  종로구    161984   151217   10767    28073
2   중구    136469   126175   10294    23794
3  용산구    246165   229579   16586    39439
4  성동구    307193   299042    8151    44728

In [34]:
# 합계 행 삭제
# pop_seoul=pop_seoul.iloc[1:,:]

In [35]:
pop_seoul.head()

구별     인구수     한국인    외국인    고령자
1  종로구  161984  151217  10767  28073
2   중구  136469  126175  10294  23794
3  용산구  246165  229579  16586  39439
4  성동구  307193  299042   8151  44728
5  광진구  365990  350417  15573  48989

In [36]:
#2 
#pop_seoul.drop(0,inplace=True)  # 행기준이 디폴트 값

### CCTV 현황


In [39]:
# CCTV에서 소계로 오름차순 정렬
CCTV_seoul.sort_values(by='소계', inplace= True)

In [41]:
CCTV_seoul.head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
9   도봉구   858     197.0   66.0    8.0    185     59    155    117     71
24  중랑구  1068       0.0    0.0    0.0    770    102    121     66      9
2   강북구  1265     243.0   88.0  141.0     74    145    254      1    319
22  종로구  1471       8.0    7.0  599.0    132    195    148    281    101
23   중구  1544      25.0  165.0  114.0     80    245    270    317    328

> CCTV 댓수가 적은 지역으로는 도봉구,중랑구,강북구,종로구, 중구 순이다

In [42]:
# CCTV에서 소계로 내림차순 정렬
CCTV_seoul.sort_values(by='소계', ascending=False).head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0   강남구  5221    1944.0  195.0  316.0    430    546    765    577    448
4   관악구  3985     430.0   56.0  419.0    487    609    619    694    671
6   구로구  3227     852.0  219.0  349.0    187    268    326    540    486
16  성북구  3003     779.0   84.0  304.0    241    279    388    285    643
21  은평구  2962    1365.0   83.0   99.0    343    180    296    229    367

> CCTV 댓수가 많은 지역으로는 강남구, 관악구, 구로구, 성북구, 은평구 순이다.

In [ ]:
### 최근 3년간 CCTV 증가율을 구해서 제일 많이 증가한 구를 검색 후 정렬
# 2016 ~2018 의 갯수와 나머지총합를 비교 

In [59]:
# 3년간 합 
CCTV_seoul['최근증가율'] = ((CCTV_seoul[['2016년','2017년','2018년']].sum(axis=1))/(CCTV_seoul.iloc[:,2:7].sum(axis=1))  ) *100
#election['electionSum']= election[['이재명','윤석열','심상정']].sum(axis=1)


In [51]:
CCTV_seoul.iloc[:,2:7].sum(axis=1)

9      515.0
24     872.0
2      691.0
22     941.0
23     629.0
5      746.0
17     974.0
3      909.0
7      769.0
11     993.0
1     1027.0
8     1342.0
12    1009.0
10    1437.0
20    1841.0
13    1235.0
19    1042.0
15    1251.0
18    1459.0
14    1840.0
21    2070.0
16    1687.0
6     1875.0
4     2001.0
0     3431.0
dtype: float64

In [62]:
# 정렬
CCTV_seoul.sort_values(by="최근증가율",ascending=False).head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년  \
23    중구  1544      25.0  165.0  114.0     80    245    270    317    328   
19  영등포구  2495     132.0  121.0  206.0    217    366    289    371    793   
15   성동구  2679     665.0  109.0  118.0    101    258    201    933    294   
7    금천구  1634      27.0   17.0  242.0    101    382    136    199    530   
5    광진구  1581     470.0   42.0   83.0     87     64     21    468    346   

         최근증가율  
23  145.468998  
19  139.443378  
15  114.148681  
7   112.483745  
5   111.930295

> 결과 : 최근 3년간 cctv가 2015년 이전에 비해 가장 많이 증가한 곳은 중구, 영등포구, 성동구, 금천구, 광진구이다

---
### 인구현황

In [64]:
# 구별 Data의 유효성 확인 
len(pop_seoul['구별'].unique())

25

In [65]:
pop_seoul.head()

구별     인구수     한국인    외국인    고령자
1  종로구  161984  151217  10767  28073
2   중구  136469  126175  10294  23794
3  용산구  246165  229579  16586  39439
4  성동구  307193  299042   8151  44728
5  광진구  365990  350417  15573  48989

In [75]:
pop_seoul['외국인비율']=(pop_seoul['외국인']) / (pop_seoul['인구수']) * 100
pop_seoul['고령자비율']=(pop_seoul['고령자']) / (pop_seoul['인구수']) * 100

In [76]:
pop_seoul.head()

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
1  종로구  161984  151217  10767  28073  6.646953  17.330724
2   중구  136469  126175  10294  23794  7.543105  17.435462
3  용산구  246165  229579  16586  39439  6.737757  16.021368
4  성동구  307193  299042   8151  44728  2.653381  14.560228
5  광진구  365990  350417  15573  48989  4.255034  13.385338

In [78]:
# 인구수가 제일 많은 지역 TOP 5 
pop_seoul.sort_values(by="인구수",ascending=False).head()

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
24  송파구  680883  674095   6788  89539  0.996941  13.150424
16  강서구  595703  589302   6401  85992  1.074529  14.435381
23  강남구  549898  544804   5094  72602  0.926354  13.202812
11  노원구  535495  531037   4458  82682  0.832501  15.440294
21  관악구  516662  499374  17288  76664  3.346095  14.838328

In [79]:
# 외국인이 제일 많은 지역 TOP 5 
pop_seoul.sort_values(by="외국인",ascending=False).head()

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
19  영등포구  404766  371903  32863  59373  8.119012  14.668475
17   구로구  438308  405837  32471  67432  7.408261  15.384615
18   금천구  251370  232583  18787  38508  7.473843  15.319251
21   관악구  516662  499374  17288  76664  3.346095  14.838328
6   동대문구  362793  346156  16637  60367  4.585811  16.639516

In [88]:
# 외국인 비율이 높은 지역 TOP 5 
pop_seoul.sort_values(by="외국인비율",ascending=False)

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
19  영등포구  404766  371903  32863  59373  8.119012  14.668475
2     중구  136469  126175  10294  23794  7.543105  17.435462
18   금천구  251370  232583  18787  38508  7.473843  15.319251
17   구로구  438308  405837  32471  67432  7.408261  15.384615
3    용산구  246165  229579  16586  39439  6.737757  16.021368
1    종로구  161984  151217  10767  28073  6.646953  17.330724
6   동대문구  362793  346156  16637  60367  4.585811  16.639516
5    광진구  365990  350417  15573  48989  4.255034  13.385338
13  서대문구  325875  312642  13233  53038  4.060759  16.275566
21   관악구  516662  499374  17288  76664  3.346095  14.838328
20   동작구  407802  395014  12788  63378  3.135836  15.541366
14   마포구  386086  374570  11516  53283  2.982755  13.800811
4    성동구  307193  299042   8151  44728  2.653381  14.560228
8    성북구  454532  442494  12038  72172  2.648438  15.878310
7    중랑구  400678  395619   5059  66764  1.262610  16.662757
9    강북구  316750  312985   3765  61660  1.188635  19.466456
16   강서구  595703  589302   6401  85992  1.074529  14.435381
24   송파구  680883  674095   6788  89539  0.996941  13.150424
22   서초구  434801  430568   4233  58332  0.973549  13.415793
25   강동구  457042  452646   4396  66401  0.961837  14.528424
12   은평구  482509  478019   4490  82245  0.930553  17.045278
23   강남구  549898  544804   5094  72602  0.926354  13.202812
15   양천구  460532  456339   4193  62761  0.910469  13.627935
11   노원구  535495  531037   4458  82682  0.832501  15.440294
10   도봉구  333495  331238   2257  60023  0.676772  17.998171

In [ ]:
> 외국인이 가장 많고 비율도 높은 곳은 영등포구 

In [83]:
# 고령자 정렬 
pop_seoul.sort_values(by="고령자",ascending=False)

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
24   송파구  680883  674095   6788  89539  0.996941  13.150424
16   강서구  595703  589302   6401  85992  1.074529  14.435381
11   노원구  535495  531037   4458  82682  0.832501  15.440294
12   은평구  482509  478019   4490  82245  0.930553  17.045278
21   관악구  516662  499374  17288  76664  3.346095  14.838328
23   강남구  549898  544804   5094  72602  0.926354  13.202812
8    성북구  454532  442494  12038  72172  2.648438  15.878310
17   구로구  438308  405837  32471  67432  7.408261  15.384615
7    중랑구  400678  395619   5059  66764  1.262610  16.662757
25   강동구  457042  452646   4396  66401  0.961837  14.528424
20   동작구  407802  395014  12788  63378  3.135836  15.541366
15   양천구  460532  456339   4193  62761  0.910469  13.627935
9    강북구  316750  312985   3765  61660  1.188635  19.466456
6   동대문구  362793  346156  16637  60367  4.585811  16.639516
10   도봉구  333495  331238   2257  60023  0.676772  17.998171
19  영등포구  404766  371903  32863  59373  8.119012  14.668475
22   서초구  434801  430568   4233  58332  0.973549  13.415793
14   마포구  386086  374570  11516  53283  2.982755  13.800811
13  서대문구  325875  312642  13233  53038  4.060759  16.275566
5    광진구  365990  350417  15573  48989  4.255034  13.385338
4    성동구  307193  299042   8151  44728  2.653381  14.560228
3    용산구  246165  229579  16586  39439  6.737757  16.021368
18   금천구  251370  232583  18787  38508  7.473843  15.319251
1    종로구  161984  151217  10767  28073  6.646953  17.330724
2     중구  136469  126175  10294  23794  7.543105  17.435462

In [87]:
# 고령자 비율 정렬 
pop_seoul.sort_values(by="고령자비율",ascending=False)

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
9    강북구  316750  312985   3765  61660  1.188635  19.466456
10   도봉구  333495  331238   2257  60023  0.676772  17.998171
2     중구  136469  126175  10294  23794  7.543105  17.435462
1    종로구  161984  151217  10767  28073  6.646953  17.330724
12   은평구  482509  478019   4490  82245  0.930553  17.045278
7    중랑구  400678  395619   5059  66764  1.262610  16.662757
6   동대문구  362793  346156  16637  60367  4.585811  16.639516
13  서대문구  325875  312642  13233  53038  4.060759  16.275566
3    용산구  246165  229579  16586  39439  6.737757  16.021368
8    성북구  454532  442494  12038  72172  2.648438  15.878310
20   동작구  407802  395014  12788  63378  3.135836  15.541366
11   노원구  535495  531037   4458  82682  0.832501  15.440294
17   구로구  438308  405837  32471  67432  7.408261  15.384615
18   금천구  251370  232583  18787  38508  7.473843  15.319251
21   관악구  516662  499374  17288  76664  3.346095  14.838328
19  영등포구  404766  371903  32863  59373  8.119012  14.668475
4    성동구  307193  299042   8151  44728  2.653381  14.560228
25   강동구  457042  452646   4396  66401  0.961837  14.528424
16   강서구  595703  589302   6401  85992  1.074529  14.435381
14   마포구  386086  374570  11516  53283  2.982755  13.800811
15   양천구  460532  456339   4193  62761  0.910469  13.627935
22   서초구  434801  430568   4233  58332  0.973549  13.415793
5    광진구  365990  350417  15573  48989  4.255034  13.385338
23   강남구  549898  544804   5094  72602  0.926354  13.202812
24   송파구  680883  674095   6788  89539  0.996941  13.150424

- 인구수가 제일 많은 지역은 송파구이지만, 영등포구가 제일 외국인이 많다.
그리고 그 근처라고 할 수 있는 구로구, 금천구 등도 굉장히 외국인이 많다.
송파구는 고령자가 제일 많지만 고령자 비율이 높지 않은 것이 확인된다
하지만 강북구, 도봉구, 중구, 종로구, 은평구 같은 경우는 
인구수 대비 고령자 비율이 많기 때문에 추후 고령화가 우려된다

---
# cctv의 인구현황 합치기

In [89]:
data_result = pd.merge(CCTV_seoul,pop_seoul, on ='구별')
 

In [91]:
data_result.head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년  \
0  도봉구   858     197.0   66.0    8.0    185     59    155    117     71   
1  중랑구  1068       0.0    0.0    0.0    770    102    121     66      9   
2  강북구  1265     243.0   88.0  141.0     74    145    254      1    319   
3  종로구  1471       8.0    7.0  599.0    132    195    148    281    101   
4   중구  1544      25.0  165.0  114.0     80    245    270    317    328   

        최근증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율  
0   66.601942  333495  331238   2257  60023  0.676772  17.998171  
1   22.477064  400678  395619   5059  66764  1.262610  16.662757  
2   83.068017  316750  312985   3765  61660  1.188635  19.466456  
3   56.323061  161984  151217  10767  28073  6.646953  17.330724  
4  145.468998  136469  126175  10294  23794  7.543105  17.435462

In [92]:
delColum = data_result.columns[2:10]

for i in delColum:
    del data_result[i]
data_result.head()

구별    소계       최근증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율
0  도봉구   858   66.601942  333495  331238   2257  60023  0.676772  17.998171
1  중랑구  1068   22.477064  400678  395619   5059  66764  1.262610  16.662757
2  강북구  1265   83.068017  316750  312985   3765  61660  1.188635  19.466456
3  종로구  1471   56.323061  161984  151217  10767  28073  6.646953  17.330724
4   중구  1544  145.468998  136469  126175  10294  23794  7.543105  17.435462

In [97]:
# index를 구벼롤 
#data_result.set_index("구별", inplace= True)

In [96]:
data_result.head()

소계       최근증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율
구별                                                                      
도봉구   858   66.601942  333495  331238   2257  60023  0.676772  17.998171
중랑구  1068   22.477064  400678  395619   5059  66764  1.262610  16.662757
강북구  1265   83.068017  316750  312985   3765  61660  1.188635  19.466456
종로구  1471   56.323061  161984  151217  10767  28073  6.646953  17.330724
중구   1544  145.468998  136469  126175  10294  23794  7.543105  17.435462

In [98]:
import numpy as np

In [100]:
# 고령자 비율과 cctv소계의 상관계수
np.corrcoef(data_result.고령자비율, data_result.소계)


array([[ 1.        , -0.44225083],
       [-0.44225083,  1.        ]])

> 역상관 : 고령자 비율이 높은 곳은 cctv의 수는 적다

In [101]:
# 고령자와  cctv소계의 상관계수
np.corrcoef(data_result.고령자, data_result.소계)

array([[1.        , 0.28638538],
       [0.28638538, 1.        ]])

In [103]:
# 외국인 비율과  cctv소계의 상관계수
np.corrcoef(data_result.외국인비율, data_result.소계)

array([[ 1.        , -0.06215538],
       [-0.06215538,  1.        ]])

In [104]:
# 외국인과  cctv소계의 상관계수
np.corrcoef(data_result.외국인, data_result.소계)

array([[1.        , 0.17444235],
       [0.17444235, 1.        ]])

In [106]:
# 인구수와  cctv소계의 상관계수
np.corrcoef(data_result.인구수, data_result.소계)

array([[1.        , 0.38064812],
       [0.38064812, 1.        ]])

> 고령자 비율의 상관계수를 보면 역상관이 발생하고 이는 고령자가 아닌 젊은 층의 비율이 높은 곳에 
CCTV가 많이 설치되는 경향을 보인다
> 주로 인구수와 양의 상관을 가지고 있어 CCTV 댓수는 인구수에 비례하여 증가하는 경향을 보인다.