<img src="../Data/all.png">

![](../Data/layer.png)

In [25]:
import pandas as pd
data = pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

#### 칼럼 소개
- admit : 합격여부 (1: 합격, 0: 불합격)
- gre : 영어성적
- gpa: 학점
- rank: 지원한 대학원 수준


### preprocessing (전처리)

In [26]:
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [27]:
# 결측치 데이터 삭제
data.dropna(inplace=True)
# 결측치 데이터를 다른값으로 대체
#data.fillna(100)

In [28]:
data.isnull().sum()
# 제거 완료

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [29]:
# rank 종류 파악
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [30]:
# 영어 점수의 최대값과 최소값
print("최대값:", data['gre'].max())
print("최소값:", data['gre'].min())

최대값: 800.0
최소값: 220.0


In [31]:
# traing data
# 입력층 
x = data[['gre','gpa','rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [32]:
# target data
# 합격 여부
# 출력층 
# 0 아니면 1의 이진분류라서 sigmoid
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [33]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

> 현재 layer(층)은 하나 => 입력층은 아니고 은닉층과 출력층, 출력층 하나만 있으므로 

---
# Deep Learning Model 만들기

In [34]:
from tensorflow import keras

In [35]:
# 입력층 
input_layer = keras.layers.InputLayer(input_shape=(3,))
# 은닉층
hidden_layer = keras.layers.Dense(256,activation="tanh")
# 출력층 
output_layer = keras.layers.Dense(1,activation="sigmoid")

In [46]:
model = keras.Sequential(
    [input_layer,
    hidden_layer,
    output_layer
    ]
)

In [47]:
# 손실함수 
model.compile(optimizer="adam",loss='binary_crossentropy',metrics = 'accuracy')
# optimizer : learning rate를 알맞게 조정해줌
# 모두 경사하강법이나 기울기가 jumping 하는 것이다 
# - adam
# - adagrad
# - adadelta
# - rmsprop
# - sgdf : 경사하강법

# loss   => 손실함수
# binary_crossentropy    => 이진분류 및 확률 예측
# metrics = 'accuracy'  => 모델 측정기준 : 정확도

In [48]:
# 학습 시키키
import numpy as np
model.fit(np.array(x),np.array(y), epochs=500)
# verbose = 0 => 진행상황 가리기 

Epoch 1/500
14/14 [==============================] - 1s 2ms/step - loss: 0.7050 - accuracy: 0.5412
Epoch 2/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6827 - accuracy: 0.5812
Epoch 3/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6794 - accuracy: 0.5435
Epoch 4/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6674 - accuracy: 0.6094
Epoch 5/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6733 - accuracy: 0.5765
Epoch 6/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6657 - accuracy: 0.5882
Epoch 7/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6604 - accuracy: 0.6282
Epoch 8/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6702 - accuracy: 0.5741
Epoch 9/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6626 - accuracy: 0.6047
Epoch 10/500
14/14 [==============================] - 0s 2ms/step - loss: 0.7068 - accuracy: 0.5224
Epoch 11/

In [50]:
# hidden layer의 가중치 값출력
hidden_layer.get_weights()[0]

array([[ 1.10561382e-02, -1.38370730e-02,  5.44210374e-02,
         1.56890228e-02,  4.06340063e-02,  3.43588814e-02,
         6.33940995e-02, -1.34534344e-01, -1.13606021e-01,
         1.50356203e-01,  3.58572826e-02,  5.27865738e-02,
         1.13016844e-01, -5.42682186e-02, -3.50403748e-02,
         1.47791849e-02,  9.68012661e-02, -4.68600467e-02,
         1.24514520e-01,  3.78104076e-02, -9.84815136e-02,
        -1.54355327e-02,  5.46152443e-02, -7.26086199e-02,
         5.12427539e-02,  1.32177055e-01,  3.74255255e-02,
         1.36493063e-02,  1.90331936e-02, -2.62324270e-02,
         1.08110875e-01,  5.25849164e-02,  1.20893121e-01,
         3.46338712e-02, -9.26542059e-02, -6.06720448e-02,
        -1.43089751e-02, -1.00483686e-01,  8.29322636e-02,
         9.24216658e-02, -1.50119677e-01,  1.15288079e-01,
        -9.77041498e-02, -3.72926034e-02, -1.12911463e-01,
        -8.78980905e-02, -1.32938787e-01, -1.37824956e-02,
        -1.34719163e-01,  6.91011846e-02, -1.19272128e-0

In [51]:
hidden_layer.get_weights()[1]

array([ 3.17361206e-01, -1.27941027e-01,  0.00000000e+00,  1.08548552e-01,
        0.00000000e+00,  4.88183880e-03,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  4.48205566e-04,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -1.67705919e-04,  1.35405034e-01,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.63879592e-05,
        0.00000000e+00, -1.01059273e-01,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.09990324e-04,  1.34354264e-01,
        4.47930098e-02, -2.00210363e-02,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  3.09689291e-04,  0.00000000e+00,  0.00000000e+00,
       -1.49744987e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -7.12486042e-07,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.11827493e-01,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  4.13327332e-04,
        0.00000000e+00,  

In [54]:
# hidden layer 출력 확인
intermediate_layer_model = keras.Model(inputs=model.input,outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [55]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[ 0.99997616, -0.9999777 ,  1.        , ..., -1.        ,
         1.        ,  1.        ],
       [ 1.        , -1.        ,  1.        , ..., -1.        ,
         1.        ,  1.        ],
       [ 1.        , -1.        ,  1.        , ..., -1.        ,
         1.        ,  1.        ],
       ...,
       [ 0.9999962 , -0.9999969 ,  1.        , ..., -1.        ,
         1.        ,  1.        ],
       [ 1.        , -1.        ,  1.        , ..., -1.        ,
         1.        ,  1.        ],
       [ 1.        , -1.        ,  1.        , ..., -1.        ,
         1.        ,  1.        ]], dtype=float32)>